import { useQuery } from '@tanstack/react-query';
import { supabase } from '../supabase';
import type { TimelineEvent, LayerRecord } from '../types/database.types';

export const SEED_LAYERS: LayerRecord[] = [
  { id: '11111111-1111-1111-1111-111111111111', key: 'deep-time', label: 'Cosmic & Deep Time', sort_order: 1 },
  { id: '22222222-2222-2222-2222-222222222222', key: 'world-history', label: 'World History', sort_order: 2 },
  { id: '33333333-3333-3333-3333-333333333333', key: 'india', label: 'India Track', sort_order: 3 },
  { id: '44444444-4444-4444-4444-444444444444', key: 'religion', label: 'Religion & Philosophy', sort_order: 4 },
  { id: '55555555-5555-5555-5555-555555555555', key: 'science-tech', label: 'Science & Tech', sort_order: 5 },
];

export const MOCK_SEED_EVENTS: TimelineEvent[] = [
  // Deep Time (e1 - e6)
  {
    id: 'e0000001-0000-0000-0000-000000000001',
    title: 'The Big Bang',
    slug: 'big-bang',
    summary: 'Origin of the observable universe, space, and time.',
    body: 'The universe originated in an infinitely dense singularity approximately 13.8 billion years ago.',
    category: 'Cosmology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd1', event_id: 'e1', precision: 'bya', calendar: 'ya', year_start: -1380000000, year_end: null, years_before_present: 13800000000, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[0]],
  },
  {
    id: 'e0000002-0000-0000-0000-000000000002',
    title: 'Formation of Earth',
    slug: 'formation-of-earth',
    summary: 'Accretion of Earth from the solar nebula.',
    body: 'Earth accreted from dust and gases surrounding the early Sun 4.54 billion years ago.',
    category: 'Geology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd2', event_id: 'e2', precision: 'bya', calendar: 'ya', year_start: -454000000, year_end: null, years_before_present: 4540000000, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[0]],
  },
  {
    id: 'e0000003-0000-0000-0000-000000000003',
    title: 'Emergence of Microbial Life',
    slug: 'first-life',
    summary: 'Earliest evidence of cellular life on Earth.',
    body: 'Stromatolites and microfossils indicate bacterial life emerged around 3.7 billion years ago.',
    category: 'Biology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd3', event_id: 'e3', precision: 'bya', calendar: 'ya', year_start: -370000000, year_end: null, years_before_present: 3700000000, confidence: 'probable', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[0]],
  },
  {
    id: 'e0000004-0000-0000-0000-000000000004',
    title: 'Cambrian Explosion',
    slug: 'cambrian-explosion',
    summary: 'Rapid diversification of complex multicellular life forms.',
    body: 'Most major animal phyla appeared in the fossil record within a short evolutionary window.',
    category: 'Biology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd4', event_id: 'e4', precision: 'mya', calendar: 'ya', year_start: -54100000, year_end: null, years_before_present: 541000000, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[0]],
  },
  {
    id: 'e0000005-0000-0000-0000-000000000005',
    title: 'Dinosaur Extinction',
    slug: 'dinosaur-extinction',
    summary: 'Chicxulub asteroid impact wipes out non-avian dinosaurs.',
    body: '75% of plant and animal species on Earth perished following an asteroid impact in present-day Mexico.',
    category: 'Paleontology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd5', event_id: 'e5', precision: 'mya', calendar: 'ya', year_start: -6600000, year_end: null, years_before_present: 66000000, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[0]],
  },
  {
    id: 'e0000006-0000-0000-0000-000000000006',
    title: 'Emergence of Homo Sapiens',
    slug: 'homo-sapiens',
    summary: 'Anatomically modern humans arise in Africa.',
    body: 'Fossil discoveries in Jebel Irhoud date earliest Homo sapiens to around 300,000 years ago.',
    category: 'Anthropology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd6', event_id: 'e6', precision: 'millennium', calendar: 'ya', year_start: -300000, year_end: null, years_before_present: 300000, confidence: 'probable', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[0]],
  },

  // World History & Prehistory Base (e7 - e11)
  {
    id: 'e0000007-0000-0000-0000-000000000007',
    title: 'Agricultural Revolution',
    slug: 'agricultural-revolution',
    summary: 'Transition to settled farming and cereal cultivation.',
    body: 'Independent domestication of crops transformed human societal structure.',
    category: 'Prehistory',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd7', event_id: 'e7', precision: 'millennium', calendar: 'ya', year_start: -12000, year_end: null, years_before_present: 12000, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000008-0000-0000-0000-000000000008',
    title: 'Construction of Göbekli Tepe',
    slug: 'gobekli-tepe',
    summary: 'Earliest known monumental sanctuary.',
    body: 'Pre-Pottery Neolithic site in Anatolia featuring carved stone pillars.',
    category: 'Archaeology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd8', event_id: 'e8', precision: 'century', calendar: 'ce_bce', year_start: -9500, year_end: null, years_before_present: 11526, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000010-0000-0000-0000-000000000010',
    title: 'Great Pyramid of Giza',
    slug: 'great-pyramid-giza',
    summary: 'Pharaoh Khufu erects monumental pyramid on the Giza plateau.',
    body: 'Constructed with over 2 million limestone blocks.',
    category: 'Architecture',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd10', event_id: 'e10', precision: 'century', calendar: 'ce_bce', year_start: -2560, year_end: null, years_before_present: 4586, confidence: 'probable', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000011-0000-0000-0000-000000000011',
    title: 'Code of Hammurabi',
    slug: 'code-of-hammurabi',
    summary: 'Babylonian legal code inscribed on a basalt stele.',
    body: 'Famous for the principle of retributive law.',
    category: 'Law',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd11', event_id: 'e11', precision: 'century', calendar: 'ce_bce', year_start: -1750, year_end: null, years_before_present: 3776, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },

  // India Track Base & Deep Track (e9, e12 - e16, e19, e22, e24, e27, e30 - e46)
  {
    id: 'e0000030-0000-0000-0000-000000000030',
    title: 'Bhimbetka Cave Paintings',
    slug: 'bhimbetka-paintings',
    summary: 'Mesolithic rock art shelters in Madhya Pradesh.',
    body: 'Pictographs depicting hunting scenes and dances represent early human artistic expression in South Asia.',
    category: 'Archaeology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd30', event_id: 'e30', precision: 'millennium', calendar: 'ya', year_start: -30000, year_end: null, years_before_present: 30000, confidence: 'probable', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000009-0000-0000-0000-000000000009',
    title: 'Indus Valley Civilization',
    slug: 'indus-valley-civilization',
    summary: 'Rise of Harappan urban planning and standardized weights.',
    body: 'Harappa and Mohenjo-daro developed sophisticated drainage systems and craft specialization.',
    category: 'Civilization',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd9', event_id: 'e9', precision: 'century', calendar: 'ce_bce', year_start: -3300, year_end: -1300, years_before_present: 5326, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000031-0000-0000-0000-000000000031',
    title: 'Decline of Harappan Cities',
    slug: 'indus-decline',
    summary: 'Urban desynchronization and post-urban shift in the Indus basin.',
    body: 'Climate aridification, river shifting (Ghaggar-Hakra), and trade dislocation led to urban abandonment.',
    category: 'Archaeology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd31', event_id: 'e31', precision: 'century', calendar: 'ce_bce', year_start: -1900, year_end: -1300, years_before_present: 3926, confidence: 'debated', confidence_note: 'Multiple competing hypotheses: monsoonal shift vs river desiccation.', is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000012-0000-0000-0000-000000000012',
    title: 'Vedic Age & Rigveda Compilation',
    slug: 'vedic-age',
    summary: 'Composition of earliest Vedic hymns in northwestern India.',
    body: 'Oral tradition of the Rigveda established sacred poetry and early philosophical inquiry.',
    category: 'Literature',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd12', event_id: 'e12', precision: 'century', calendar: 'ce_bce', year_start: -1500, year_end: -500, years_before_present: 3526, confidence: 'debated', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000032-0000-0000-0000-000000000032',
    title: 'Rise of Magadha & Mahajanapadas',
    slug: 'mahajanapadas-magadha',
    summary: 'Emergence of 16 major territorial states in northern India.',
    body: 'Magadha under Bimbisara and Ajatashatru established regional dominance along the Gangetic plain.',
    category: 'Statecraft',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd32', event_id: 'e32', precision: 'century', calendar: 'ce_bce', year_start: -600, year_end: -345, years_before_present: 2626, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000013-0000-0000-0000-000000000013',
    title: 'Life of Mahavira',
    slug: 'mahavira',
    summary: '24th Tirthankara of Jainism revitalizes Ahimsa philosophy.',
    body: 'Promoted non-violence and ascetic vows across ancient Magadha.',
    category: 'Religion',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd13', event_id: 'e13', precision: 'year', calendar: 'ce_bce', year_start: -599, year_end: -527, years_before_present: 2625, confidence: 'traditional', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2], SEED_LAYERS[3]],
  },
  {
    id: 'e0000014-0000-0000-0000-000000000014',
    title: 'Life of Gautama Buddha',
    slug: 'buddha',
    summary: 'Founder of Buddhism teaches the Four Noble Truths.',
    body: 'Attained Enlightenment under the Bodhi tree in Bodh Gaya.',
    category: 'Religion',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd14', event_id: 'e14', precision: 'year', calendar: 'ce_bce', year_start: -563, year_end: -483, years_before_present: 2589, confidence: 'probable', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2], SEED_LAYERS[3]],
  },
  {
    id: 'e0000015-0000-0000-0000-000000000015',
    title: 'Mauryan Empire Founded',
    slug: 'mauryan-empire',
    summary: 'Chandragupta Maurya unifies northern India with Chanakya.',
    body: 'Established the first pan-Indian empire with Magadha as its political center.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd15', event_id: 'e15', precision: 'year', calendar: 'ce_bce', year_start: -322, year_end: -185, years_before_present: 2348, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000016-0000-0000-0000-000000000016',
    title: 'Edicts of Ashoka',
    slug: 'edicts-of-ashoka',
    summary: 'Emperor Ashoka propagates Dhamma and non-violence.',
    body: 'Inscriptions carved on rock faces and polished sandstone pillars.',
    category: 'Governance',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd16', event_id: 'e16', precision: 'year', calendar: 'ce_bce', year_start: -268, year_end: -232, years_before_present: 2294, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000017-0000-0000-0000-000000000017',
    title: 'Qin Dynasty Unification of China',
    slug: 'qin-unification',
    summary: 'Qin Shi Huang unifies China into first imperial dynasty.',
    body: 'Standardized currency and built the Great Wall.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd17', event_id: 'e17', precision: 'year', calendar: 'ce_bce', year_start: -221, year_end: -206, years_before_present: 2247, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000018-0000-0000-0000-000000000018',
    title: 'Establishment of Roman Empire',
    slug: 'roman-empire',
    summary: 'Augustus becomes first Roman Emperor.',
    body: 'Pax Romana across Mediterranean.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd18', event_id: 'e18', precision: 'year', calendar: 'ce_bce', year_start: -27, year_end: 476, years_before_present: 2053, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000019-0000-0000-0000-000000000019',
    title: 'Gupta Empire Golden Age',
    slug: 'gupta-empire',
    summary: 'Classical age of Indian mathematics, astronomy, literature.',
    body: 'Aryabhata calculates pi and heliocentrism; Kalidasa writes Sanskrit drama.',
    category: 'Culture',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd19', event_id: 'e19', precision: 'year', calendar: 'ce_bce', year_start: 320, year_end: 550, years_before_present: 1706, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000033-0000-0000-0000-000000000033',
    title: 'Publication of Aryabhatiya',
    slug: 'aryabhatiya',
    summary: 'Aryabhata formulates mathematical astronomy and zero place-value concept.',
    body: 'Sanskrit astronomical treatise calculating Earth rotation on its axis and solar eclipses.',
    category: 'Science',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd33', event_id: 'e33', precision: 'year', calendar: 'ce_bce', year_start: 499, year_end: null, years_before_present: 1527, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2], SEED_LAYERS[4]],
  },
  {
    id: 'e0000020-0000-0000-0000-000000000020',
    title: 'Birth & Rise of Islam',
    slug: 'rise-of-islam',
    summary: 'Prophet Muhammad establishes Islamic faith in Arabia.',
    body: 'The Quranic revelation created an expansive civilization.',
    category: 'Religion',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd20', event_id: 'e20', precision: 'year', calendar: 'ce_bce', year_start: 570, year_end: 632, years_before_present: 1456, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[3]],
  },
  {
    id: 'e0000021-0000-0000-0000-000000000021',
    title: 'Tang Dynasty Golden Age',
    slug: 'tang-dynasty',
    summary: 'High period of Chinese poetry and Silk Road commerce.',
    body: 'Capital Chang\'an became world\'s largest urban center.',
    category: 'Civilization',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd21', event_id: 'e21', precision: 'year', calendar: 'ce_bce', year_start: 618, year_end: 907, years_before_present: 1408, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000022-0000-0000-0000-000000000022',
    title: 'Chola Maritime Expeditions',
    slug: 'chola-maritime-expedition',
    summary: 'Rajendra Chola I launches naval campaigns into Southeast Asia.',
    body: 'Established maritime trade dominance across Bay of Bengal.',
    category: 'Naval',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd22', event_id: 'e22', precision: 'year', calendar: 'ce_bce', year_start: 1014, year_end: 1044, years_before_present: 1012, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },

  // Delhi Sultanate & Medieval India (e34 - e37)
  {
    id: 'e0000034-0000-0000-0000-000000000034',
    title: 'Establishment of Delhi Sultanate (Mamluk Dynasty)',
    slug: 'delhi-sultanate-mamluk',
    summary: 'Qutb ud-Din Aibak establishes first Sultanate dynasty in Delhi.',
    body: 'Initiated Turkic-Afghan rule in northern India and construction of Qutb Minar complex.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd34', event_id: 'e34', precision: 'year', calendar: 'ce_bce', year_start: 1206, year_end: 1290, years_before_present: 820, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000035-0000-0000-0000-000000000035',
    title: 'Khalji Dynasty Expansion',
    slug: 'khalji-dynasty',
    summary: 'Alauddin Khalji expands Sultanate hegemony into the Deccan.',
    body: 'Reformed agrarian revenue controls and repelled Chagatai Mongol incursions.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd35', event_id: 'e35', precision: 'year', calendar: 'ce_bce', year_start: 1290, year_end: 1320, years_before_present: 736, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000036-0000-0000-0000-000000000036',
    title: 'Tughlaq Dynasty Reign & Capital Shift',
    slug: 'tughlaq-dynasty',
    summary: 'Muhammad bin Tughlaq transfers capital to Daulatabad.',
    body: 'Introduced token copper currency and expanded administrative apparatus into Southern India.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd36', event_id: 'e36', precision: 'year', calendar: 'ce_bce', year_start: 1320, year_end: 1414, years_before_present: 706, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000037-0000-0000-0000-000000000037',
    title: 'Founding of Vijayanagara Empire',
    slug: 'vijayanagara-empire',
    summary: 'Harihara I and Bukka Raya I found Hindu empire in the Deccan.',
    body: 'Capital city Hampi became premier center of South Indian architecture and Carnatic culture.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd37', event_id: 'e37', precision: 'year', calendar: 'ce_bce', year_start: 1336, year_end: 1646, years_before_present: 690, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000023-0000-0000-0000-000000000023',
    title: 'Movable Type Printing Press',
    slug: 'gutenberg-press',
    summary: 'Johannes Gutenberg perfects mechanical printing in Europe.',
    body: 'Democratized access to written knowledge.',
    category: 'Invention',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd23', event_id: 'e23', precision: 'year', calendar: 'ce_bce', year_start: 1440, year_end: null, years_before_present: 586, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[4]],
  },

  // Mughal & Early Modern India (e24, e38 - e42)
  {
    id: 'e0000024-0000-0000-0000-000000000024',
    title: 'Founding of Mughal Empire',
    slug: 'mughal-empire',
    summary: 'Babur defeats Ibrahim Lodi at First Battle of Panipat.',
    body: 'Synthesized Indo-Persian culture and administration.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd24', event_id: 'e24', precision: 'year', calendar: 'ce_bce', year_start: 1526, year_end: 1857, years_before_present: 500, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000038-0000-0000-0000-000000000038',
    title: 'Construction of the Taj Mahal',
    slug: 'taj-mahal-construction',
    summary: 'Shah Jahan erects white marble mausoleum for Mumtaz Mahal.',
    body: 'Peak monument of Mughal architecture on the Yamuna riverbank in Agra.',
    category: 'Architecture',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd38', event_id: 'e38', precision: 'year', calendar: 'ce_bce', year_start: 1632, year_end: 1653, years_before_present: 394, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000039-0000-0000-0000-000000000039',
    title: 'Coronation of Shivaji Maharaj (Maratha Empire)',
    slug: 'maratha-empire-coronation',
    summary: 'Shivaji Maharaj crowned Chhatrapati at Raigad Fort.',
    body: 'Established independent sovereign Maratha state with naval and fort defenses.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd39', event_id: 'e39', precision: 'exact', calendar: 'ce_bce', year_start: 1674, year_end: null, years_before_present: 352, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000025-0000-0000-0000-000000000025',
    title: 'Newton\'s Principia Published',
    slug: 'newton-principia',
    summary: 'Isaac Newton formulates laws of motion and gravitation.',
    body: 'Laid mathematical foundations of modern physics.',
    category: 'Science',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd25', event_id: 'e25', precision: 'year', calendar: 'ce_bce', year_start: 1687, year_end: null, years_before_present: 339, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[4]],
  },
  {
    id: 'e0000040-0000-0000-0000-000000000040',
    title: 'Battle of Plassey',
    slug: 'battle-of-plassey',
    summary: 'East India Company defeats Siraj-ud-Daulah in Bengal.',
    body: 'Robert Clive secures British territorial tax collection rights (Diwani) in Bengal.',
    category: 'War',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd40', event_id: 'e40', precision: 'exact', calendar: 'ce_bce', year_start: 1757, year_end: null, years_before_present: 269, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000026-0000-0000-0000-000000000026',
    title: 'Industrial Revolution Begins',
    slug: 'industrial-revolution',
    summary: 'Transition to steam power and manufacturing.',
    body: 'Transformed global economics.',
    category: 'Technology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd26', event_id: 'e26', precision: 'decade', calendar: 'ce_bce', year_start: 1760, year_end: 1840, years_before_present: 266, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[4]],
  },
  {
    id: 'e0000041-0000-0000-0000-000000000041',
    title: 'Founding of the Sikh Empire',
    slug: 'sikh-empire-founding',
    summary: 'Maharaja Ranjit Singh captures Lahore to unify Punjab.',
    body: 'Modernized army and secular administration in northwestern South Asia.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd41', event_id: 'e41', precision: 'year', calendar: 'ce_bce', year_start: 1799, year_end: 1849, years_before_present: 227, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000042-0000-0000-0000-000000000042',
    title: 'Indian Uprising of 1857',
    slug: 'indian-rebellion-1857',
    summary: 'Widespread rebellion against East India Company rule.',
    body: 'Led to dissolution of EIC and direct governance under the British Crown.',
    category: 'Uprising',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd42', event_id: 'e42', precision: 'year', calendar: 'ce_bce', year_start: 1857, year_end: 1858, years_before_present: 169, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000043-0000-0000-0000-000000000043',
    title: 'Swadeshi Movement & Bengal Partition',
    slug: 'swadeshi-movement',
    summary: 'Boycott of British goods following Lord Curzon\'s partition of Bengal.',
    body: 'Sparked self-reliance institutions and national indigenous manufacturing.',
    category: 'Movement',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd43', event_id: 'e43', precision: 'year', calendar: 'ce_bce', year_start: 1905, year_end: 1911, years_before_present: 121, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000044-0000-0000-0000-000000000044',
    title: 'Non-Cooperation Movement Launched',
    slug: 'non-cooperation-movement',
    summary: 'Mahatma Gandhi leads nationwide non-violent resistance after Jallianwala Bagh.',
    body: 'First major mass campaign mobilizing rural and urban populations.',
    category: 'Movement',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd44', event_id: 'e44', precision: 'year', calendar: 'ce_bce', year_start: 1920, year_end: 1922, years_before_present: 106, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000045-0000-0000-0000-000000000045',
    title: 'Salt Satyagraha (Dandi March)',
    slug: 'salt-march-satyagraha',
    summary: '240-mile march against British colonial salt tax monopoly.',
    body: 'Galvanized global international media coverage and mass civil disobedience.',
    category: 'Movement',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd45', event_id: 'e45', precision: 'exact', calendar: 'ce_bce', year_start: 1930, year_end: null, years_before_present: 96, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000046-0000-0000-0000-000000000046',
    title: 'Quit India Movement & INA Campaign',
    slug: 'quit-india-ina',
    summary: 'Mahatma Gandhi calls for immediate British exit; Subhas Chandra Bose forms INA.',
    body: 'Parallel civil disobedience and armed military campaigns during World War II.',
    category: 'Movement',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd46', event_id: 'e46', precision: 'year', calendar: 'ce_bce', year_start: 1942, year_end: 1945, years_before_present: 84, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },
  {
    id: 'e0000027-0000-0000-0000-000000000027',
    title: 'Indian Independence & Partition',
    slug: 'indian-independence',
    summary: 'India gains independence from British colonial rule.',
    body: 'Mahatma Gandhi and Jawaharlal Nehru lead the nation into democratic statehood.',
    category: 'Modern History',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd27', event_id: 'e27', precision: 'exact', calendar: 'ce_bce', year_start: 1947, year_end: null, years_before_present: 79, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[2]],
  },

  // Global Modern & Science Base (e28, e29)
  {
    id: 'e0000028-0000-0000-0000-000000000028',
    title: 'Apollo 11 Moon Landing',
    slug: 'apollo-11-moon-landing',
    summary: 'Neil Armstrong walks on the Moon.',
    body: 'Humanity steps beyond Earth orbit.',
    category: 'Space',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd28', event_id: 'e28', precision: 'exact', calendar: 'ce_bce', year_start: 1969, year_end: null, years_before_present: 57, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[4]],
  },
  {
    id: 'e0000029-0000-0000-0000-000000000029',
    title: 'Invention of World Wide Web',
    slug: 'world-wide-web',
    summary: 'Tim Berners-Lee introduces HTTP and HTML.',
    body: 'Global hyperlinked network.',
    category: 'Technology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd29', event_id: 'e29', precision: 'exact', calendar: 'ce_bce', year_start: 1989, year_end: null, years_before_present: 37, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[4]],
  },

  // Europe Track Expansion (e47 - e52)
  {
    id: 'e0000047-0000-0000-0000-000000000047',
    title: 'Classical Greek Golden Age',
    slug: 'classical-greece',
    summary: 'Periclean Athens lays foundation of Western philosophy and democracy.',
    body: 'Socrates, Plato, Aristotle, and Aeschylus flourish in Athenian city-state culture.',
    category: 'Philosophy',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd47', event_id: 'e47', precision: 'century', calendar: 'ce_bce', year_start: -500, year_end: -323, years_before_present: 2526, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000048-0000-0000-0000-000000000048',
    title: 'Assassination of Julius Caesar',
    slug: 'julius-caesar-assassination',
    summary: 'Roman senators assassinate Caesar on the Ides of March.',
    body: 'Sparked civil wars leading to the dissolution of the Roman Republic and rise of the Empire under Augustus.',
    category: 'Political',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd48', event_id: 'e48', precision: 'exact', calendar: 'ce_bce', year_start: -44, year_end: null, years_before_present: 2070, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000049-0000-0000-0000-000000000049',
    title: 'Fall of Western Roman Empire',
    slug: 'fall-of-western-roman-empire',
    summary: 'Odoacer deposes Romulus Augustulus in Rome.',
    body: 'Marks transition from Classical Antiquity to Early Medieval feudal Europe.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd49', event_id: 'e49', precision: 'year', calendar: 'ce_bce', year_start: 476, year_end: null, years_before_present: 1550, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000050-0000-0000-0000-000000000050',
    title: 'European Renaissance Begins',
    slug: 'european-renaissance',
    summary: 'Rebirth of Classical art, humanism, and literature in Italian city-states.',
    body: 'Leonardo da Vinci, Michelangelo, and Petrarch spark cultural movement from Florence across Europe.',
    category: 'Culture',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd50', event_id: 'e50', precision: 'century', calendar: 'ce_bce', year_start: 1350, year_end: 1600, years_before_present: 676, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000051-0000-0000-0000-000000000051',
    title: 'Protestant Reformation',
    slug: 'protestant-reformation',
    summary: 'Martin Luther posts Ninety-five Theses in Wittenberg.',
    body: 'Challenged papal authority, splitting Western Christianity into Catholic and Protestant denominations.',
    category: 'Religion',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd51', event_id: 'e51', precision: 'year', calendar: 'ce_bce', year_start: 1517, year_end: 1648, years_before_present: 509, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1], SEED_LAYERS[3]],
  },
  {
    id: 'e0000052-0000-0000-0000-000000000052',
    title: 'Copernican Scientific Revolution',
    slug: 'scientific-revolution',
    summary: 'Nicolaus Copernicus publishes heliocentric astronomical model.',
    body: 'Galileo and Kepler establish empirical scientific method.',
    category: 'Science',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd52', event_id: 'e52', precision: 'year', calendar: 'ce_bce', year_start: 1543, year_end: 1687, years_before_present: 483, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[4]],
  },

  // East Asia Track Expansion (e54 - e58)
  {
    id: 'e0000054-0000-0000-0000-000000000054',
    title: 'Song Dynasty Technological Innovations',
    slug: 'song-dynasty-innovations',
    summary: 'Pioneered paper currency, mariner compass, and gunpowder warfare.',
    body: 'Commercial revolution and neo-Confucian scholarship in Kaifeng and Hangzhou.',
    category: 'Technology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd54', event_id: 'e54', precision: 'year', calendar: 'ce_bce', year_start: 960, year_end: 1279, years_before_present: 1066, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1], SEED_LAYERS[4]],
  },
  {
    id: 'e0000055-0000-0000-0000-000000000055',
    title: 'Mongol Conquests & Yuan Dynasty',
    slug: 'mongol-empire-yuan',
    summary: 'Kublai Khan establishes Yuan Dynasty in Dadu (Beijing).',
    body: 'Pax Mongolica enabled trans-Eurasian trade along the Silk Road connecting Europe to China.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd55', event_id: 'e55', precision: 'year', calendar: 'ce_bce', year_start: 1271, year_end: 1368, years_before_present: 755, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000056-0000-0000-0000-000000000056',
    title: 'Ming Dynasty Construction of Forbidden City',
    slug: 'ming-forbidden-city',
    summary: 'Yongle Emperor constructs imperial palace complex in Beijing.',
    body: 'Sponsored Zheng He naval expeditions into the Indian Ocean.',
    category: 'Architecture',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd56', event_id: 'e56', precision: 'year', calendar: 'ce_bce', year_start: 1420, year_end: null, years_before_present: 606, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000057-0000-0000-0000-000000000057',
    title: 'Tokugawa Shogunate Isolation (Sakoku)',
    slug: 'tokugawa-shogunate-edo',
    summary: 'Tokugawa Ieyasu unifies Japan, initiating 250 years of peace in Edo.',
    body: 'Enforced maritime isolation policy while patronizing Kabuki and Ukiyo-e arts.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd57', event_id: 'e57', precision: 'year', calendar: 'ce_bce', year_start: 1603, year_end: 1867, years_before_present: 423, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000058-0000-0000-0000-000000000058',
    title: 'Meiji Restoration in Japan',
    slug: 'meiji-restoration',
    summary: 'Restoration of imperial rule under Emperor Meiji sparks industrialization.',
    body: 'Abolished samurai feudalism and modernized military, legal, and educational institutions.',
    category: 'Modern History',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd58', event_id: 'e58', precision: 'year', calendar: 'ce_bce', year_start: 1868, year_end: null, years_before_present: 158, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },

  // Middle East / Islamic World Track Expansion (e59 - e61)
  {
    id: 'e0000059-0000-0000-0000-000000000059',
    title: 'Abbasid Caliphate & House of Wisdom',
    slug: 'abbasid-house-of-wisdom',
    summary: 'Caliph Harun al-Rashid founds translation center in Baghdad.',
    body: 'Islamic Golden Age characterized by scientific, medical, and algebraic breakthroughs by Al-Khwarizmi and Ibn Sina.',
    category: 'Science',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd59', event_id: 'e59', precision: 'year', calendar: 'ce_bce', year_start: 750, year_end: 1258, years_before_present: 1276, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1], SEED_LAYERS[4]],
  },
  {
    id: 'e0000060-0000-0000-0000-000000000060',
    title: 'Fall of Constantinople to Ottoman Empire',
    slug: 'fall-of-constantinople',
    summary: 'Sultan Mehmed II conquers Byzantine capital city.',
    body: 'Ended Byzantine Empire, establishing Constantinople (Istanbul) as Ottoman capital.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd60', event_id: 'e60', precision: 'exact', calendar: 'ce_bce', year_start: 1453, year_end: null, years_before_present: 573, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000061-0000-0000-0000-000000000061',
    title: 'Reign of Suleiman the Magnificent',
    slug: 'suleiman-the-magnificent-reign',
    summary: 'Ottoman Empire expands to peak territorial extent across three continents.',
    body: 'Patronized architect Mimar Sinan and codified Ottoman legal law.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd61', event_id: 'e61', precision: 'year', calendar: 'ce_bce', year_start: 1520, year_end: 1566, years_before_present: 506, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },

  // Africa Track Expansion (e62 - e65)
  {
    id: 'e0000062-0000-0000-0000-000000000062',
    title: 'Kingdom of Aksum Adoption of Christianity',
    slug: 'aksum-christianity',
    summary: 'King Ezana adopts Christianity in Ethiopian highlands.',
    body: 'Minted gold coins and erected ge`ez stelae markers.',
    category: 'Religion',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd62', event_id: 'e62', precision: 'century', calendar: 'ce_bce', year_start: 330, year_end: null, years_before_present: 1696, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1], SEED_LAYERS[3]],
  },
  {
    id: 'e0000063-0000-0000-0000-000000000063',
    title: 'Mali Empire & Mansa Musa Hajj',
    slug: 'mali-empire-mansa-musa',
    summary: 'Mansa Musa travels to Mecca, highlighting West African wealth.',
    body: 'Timbuktu became leading center of Islamic manuscripts and gold trade.',
    category: 'Empire',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd63', event_id: 'e63', precision: 'year', calendar: 'ce_bce', year_start: 1324, year_end: null, years_before_present: 702, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000064-0000-0000-0000-000000000064',
    title: 'Great Zimbabwe Stone City Peak',
    slug: 'great-zimbabwe-peak',
    summary: 'Bantu kingdom constructs dry-stone monumental enclosure walls.',
    body: 'Center of Indian Ocean gold and ivory trade.',
    category: 'Archaeology',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd64', event_id: 'e64', precision: 'century', calendar: 'ce_bce', year_start: 1300, year_end: 1450, years_before_present: 726, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000065-0000-0000-0000-000000000065',
    title: 'Transatlantic Slave Trade',
    slug: 'transatlantic-slave-trade',
    summary: 'Forced migration of over 12 million Africans across the Atlantic.',
    body: 'Driven by plantation economies in European colonies across the Americas.',
    category: 'Human Rights',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd65', event_id: 'e65', precision: 'century', calendar: 'ce_bce', year_start: 1500, year_end: 1867, years_before_present: 526, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },

  // Americas Track Expansion (e66 - e71)
  {
    id: 'e0000066-0000-0000-0000-000000000066',
    title: 'Classic Maya Civilization Peak',
    slug: 'classic-maya-peak',
    summary: 'Urban centers Tikal, Calakmul, and Palenque flourish in Mesoamerica.',
    body: 'Developed sophisticated astronomical calendars, vigesimal mathematics, and logosyllabic writing.',
    category: 'Civilization',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd66', event_id: 'e66', precision: 'century', calendar: 'ce_bce', year_start: 250, year_end: 900, years_before_present: 1776, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000067-0000-0000-0000-000000000067',
    title: 'Founding of Tenochtitlan (Aztec Capital)',
    slug: 'tenochtitlan-founding',
    summary: 'Mexica people establish island capital in Lake Texcoco.',
    body: 'Constructed chinampa agricultural terraces and monumental Sun Pyramid temples.',
    category: 'Civilization',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd67', event_id: 'e67', precision: 'year', calendar: 'ce_bce', year_start: 1325, year_end: null, years_before_present: 701, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000068-0000-0000-0000-000000000068',
    title: 'Inca Construction of Machu Picchu',
    slug: 'machu-picchu-construction',
    summary: 'Pachacuti constructs royal estate high in the Andes.',
    body: 'Masterwork of dry-stone ashlar masonry without mortar.',
    category: 'Architecture',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd68', event_id: 'e68', precision: 'year', calendar: 'ce_bce', year_start: 1450, year_end: null, years_before_present: 576, confidence: 'probable', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000069-0000-0000-0000-000000000069',
    title: 'Spanish Conquest of the Aztec Empire',
    slug: 'spanish-conquest-aztec',
    summary: 'Hernán Cortés captures Tenochtitlan with indigenous Tlaxcalan allies.',
    body: 'Smallpox epidemics and siege destroyed Tenochtitlan, establishing New Spain.',
    category: 'Conquest',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd69', event_id: 'e69', precision: 'year', calendar: 'ce_bce', year_start: 1519, year_end: 1521, years_before_present: 507, confidence: 'debated', confidence_note: 'Pre-contact indigenous population death rates remain subject to demographic estimation debate.', is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000070-0000-0000-0000-000000000070',
    title: 'Spanish Conquest of the Inca Empire',
    slug: 'spanish-conquest-inca',
    summary: 'Francisco Pizarro captures Atahualpa at Battle of Cajamarca.',
    body: 'Dismantled Tawantinsuyu imperial administration to establish Viceroyalty of Peru.',
    category: 'Conquest',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd70', event_id: 'e70', precision: 'year', calendar: 'ce_bce', year_start: 1532, year_end: 1572, years_before_present: 494, confidence: 'debated', confidence_note: 'Casualty figures and disease mortality rates are based on colonial chronicle estimates.', is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
  {
    id: 'e0000071-0000-0000-0000-000000000071',
    title: 'American Declaration of Independence',
    slug: 'american-independence',
    summary: 'Thirteen North American colonies declare independence from Great Britain.',
    body: 'Adopted Thomas Jefferson drafting of constitutional democratic rights.',
    category: 'Modern History',
    created_at: '2026-08-16T00:00:00Z',
    status: 'published',
    date: { id: 'd71', event_id: 'e71', precision: 'exact', calendar: 'ce_bce', year_start: 1776, year_end: null, years_before_present: 250, confidence: 'well_established', confidence_note: null, is_primary: true },
    layers: [SEED_LAYERS[1]],
  },
];

export async function fetchLayers(): Promise<LayerRecord[]> {
  try {
    const { data, error } = await supabase
      .from('layers')
      .select('*')
      .order('sort_order', { ascending: true });

    if (error || !data || data.length === 0) {
      return SEED_LAYERS;
    }
    return data as LayerRecord[];
  } catch {
    return SEED_LAYERS;
  }
}

export async function fetchEvents(): Promise<TimelineEvent[]> {
  try {
    const { data: eventsData, error: eventsError } = await supabase
      .from('events')
      .select(`
        *,
        event_dates(*),
        event_layers(
          layers(*)
        )
      `)
      .order('created_at', { ascending: true });

    if (eventsError || !eventsData || eventsData.length === 0) {
      return MOCK_SEED_EVENTS;
    }

    return eventsData.map((e: any) => ({
      id: e.id,
      title: e.title,
      slug: e.slug,
      summary: e.summary,
      body: e.body,
      category: e.category,
      created_at: e.created_at,
      status: e.status,
      date: Array.isArray(e.event_dates) && e.event_dates.length > 0
        ? e.event_dates[0]
        : {
            id: `d-${e.id}`,
            event_id: e.id,
            precision: 'year',
            calendar: 'ce_bce',
            year_start: 2026,
            year_end: null,
            years_before_present: 0,
            confidence: 'well_established',
            confidence_note: null,
            is_primary: true,
          },
      layers: (e.event_layers || [])
        .map((el: any) => el.layers)
        .filter(Boolean),
    }));
  } catch {
    return MOCK_SEED_EVENTS;
  }
}

export function useLayers() {
  return useQuery({
    queryKey: ['layers'],
    queryFn: fetchLayers,
    placeholderData: SEED_LAYERS,
  });
}

export function useEvents() {
  return useQuery({
    queryKey: ['events'],
    queryFn: fetchEvents,
    placeholderData: MOCK_SEED_EVENTS,
  });
}
